name: Deploy Nuxt Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your main branch is named differently

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for Nuxt's static export

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Nuxt Docs
        run: pnpm run --filter=apps/docs build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-artifact@v4
        with:
          path: apps/docs/.output/public  # Ensure this matches Nuxt's static output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
